### ISSUE TITLE
"Invalid page" when clicking a pagination page

### ISSUE THREAD

**Issue by peterbe** [mozilla/delivery-console#588]
https://sentry.prod.mozaws.net/operations/deliveryconsole-stage/issues/4942951/

```
APIError: Invalid page.
  at new vt (utils/api.js:4:16)
  at call (utils/api.js:71:13)
...
(2 additional frame(s) were not displayed)
```

**Comment by peterbe** [comment]
Seems you have to go to https://sentry.prod.mozaws.net/operations/deliveryconsole-stage/issues/4942951/events/25634811/ to get the "Invalid page" error.

**Comment by peterbe** [comment]
Go to a page like `localhost:3000/recipe/?page=99` and it will trigger the XHR request `/api/v2/recipe/?ordering=-last_updated&page=99` which returns a 404. It should probably not be a 404 but a 400 instead but that's possibly unrelated and might depend on the [v3 upgrade/switch](https://github.com/mozilla/delivery-console/pull/638).

Either way, there's no feedback to the user that the XHR request failed. It should. 

Tackling this issue might conflict with this one: https://github.com/mozilla/delivery-console/pull/675
