### ISSUE TITLE
"APIError: Bad Request" when viewing a recipe

### ISSUE THREAD

**Issue by peterbe** [mozilla/delivery-console#711]
https://sentry.prod.mozaws.net/operations/deliveryconsole-stage/issues/5127023/

```
APIError: Bad Request
  at new vt (/static/js/main.bf4cec46.js:1:1425243)
  at n.<anonymous> (/static/js/main.bf4cec46.js:1:1426622)
  at _ (/static/js/main.bf4cec46.js:1:1232632)
  at Generator.l._invoke (/static/js/main.bf4cec46.js:1:1232427)
  at Generator.e.(anonymous function) [as next] (/static/js/main.bf4cec46.js:1:1232811)
...
(2 additional frame(s) were not displayed)
```

**Comment by peterbe** [comment]
The URL is `https://delivery-console.stage.mozaws.net/recipe/699/` and I don't know how that could cause a XHR to get the recipe with a Bad Request. 
Either way, the XHR error should be better handled.
